language: python
python:
  - "3.4"
install:
  - python setup.py
script:
  - python common/shapp.py
  - python common/sheventhandler.py
  - python common/shutil.py
  - python common/shregistry.py
  - python engine/restinterface.py
  - python engine/memorymanager.py
  - python feed/feed.home.tracer.py --help
  - python feed/feed.home.apcups.py --help
  - python feed/feed.home.autelis.py --help
