language: python
python:
  - "3.4"
install:
  - python setup.py
script:
  - python common/shconfig.py
  - python common/sheventhandler.py
  - python common/shutil.py
  - python common/shregistry.py
  - python engine/restinterface.py
  - python engine/memorymanager.py
