influxdb:
  image: tutum/influxdb
  #volumes:
    #- ./data:/data
  ports:
    - "8080:8080"
    - "8083:8083"
    - "8086:8086"
  expose:
    - "8088"
    - "8090"
    - "8099"
  environment:
    - PRE_CREATE_DB=Home
grafana:
  image: grafana/grafana
  ports:
    - "3000:3000"
  environment:
    - INFLUXDB_HOST=influxdb
    - INFLUXDB_PORT=8086
    - INFLUXDB_NAME=Home
    - INFLUXDB_USER=root
    - INFLUXDB_PASS=root
  links:
    - influxdb:influxdb
sentienthome:
  image: fxstein/sentienthome
  volumes:
    - ./data:/data
    - ~/.config/sentienthome/sentienthome.conf:/etc/sentienthome.conf
  ports:
    - "9001:9001" # supervisor
    - "8888:8888" # event engine
  links:
    - influxdb:influxdb
